import { useMemo, useState } from "react";
import Header from "../components/Header";
import StateChatDeviceTablet from "../components/StateChatDeviceTablet";
import DeviceTablet5 from "../components/DeviceTablet5";
import MessageFromAnotherUserDev from "../components/MessageFromAnotherUserDev";
import StateDefaultVariantMessage from "../components/StateDefaultVariantMessage";

const DChatMessage = () => {
  const [user, setUser] = useState(true);

  return (
    <div className="w-full relative bg-neutral-900 h-[1024px] overflow-hidden">
      <Header user={user} />
      <div className="absolute top-[129px] left-[312px] rounded-2xl bg-white-8 w-[1080px] overflow-hidden flex flex-row items-start justify-start">
        <div className="bg-neutral-800 h-[853px] overflow-hidden flex flex-col items-start justify-start">
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
          <StateChatDeviceTablet
            rectangle2002="/rectangle-2002@2x.png"
            userName="User name"
            lastMessage="Desc"
            date="09 Apr 2024"
            time="18:35"
            stateChatDeviceTabletGap="16px"
            stateChatDeviceTabletAlignSelf="unset"
            stateChatDeviceTabletWidth="252px"
            rectangleIconWidth="40px"
            rectangleIconHeight="40px"
            userNameFontSize="14px"
            userNameLineHeight="20px"
            descFontSize="12px"
            descLineHeight="16px"
            dateTimeGap="2px"
            apr2024FontSize="10px"
            apr2024LineHeight="12px"
            divFontSize="10px"
            divLineHeight="12px"
          />
        </div>
        <div className="flex-1 flex flex-col items-start justify-start gap-[340px]">
          <div className="self-stretch flex flex-col items-center justify-start gap-[24px]">
            <DeviceTablet5
              ellipse1250="/ellipse-1250@2x.png"
              userName="Oksana Ferrum"
              deviceTabletWidth="unset"
              deviceTabletPosition="unset"
              deviceTabletTop="unset"
              deviceTabletRight="unset"
              deviceTabletLeft="unset"
              deviceTabletAlignSelf="stretch"
            />
            <div className="w-[756px] relative h-72">
              <MessageFromAnotherUserDev
                fromUserText="All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary as necessary "
                time="18:35"
                messageFromAnotherUserDevWidth="unset"
                messageFromAnotherUserDevPosition="absolute"
                messageFromAnotherUserDevTop="0px"
                messageFromAnotherUserDevRight="unset"
                messageFromAnotherUserDevLeft="calc(50% - 378px)"
                messageFromAnotherUserDevBorderRadius="0px 16px 16px 16px"
                allTheLoremFlex="unset"
                allTheLoremWidth="676px"
                allTheLoremDisplay="inline-block"
              />
              <MessageFromAnotherUserDev
                fromUserText="All the Lorem Ipsum generators on the Internet tend to repeat predefined"
                time="18:35"
                messageFromAnotherUserDevWidth="479px"
                messageFromAnotherUserDevPosition="absolute"
                messageFromAnotherUserDevTop="208px"
                messageFromAnotherUserDevRight="unset"
                messageFromAnotherUserDevLeft="calc(50% - 378px)"
                messageFromAnotherUserDevBorderRadius="0px 16px 16px 16px"
                allTheLoremFlex="1"
                allTheLoremWidth="unset"
                allTheLoremDisplay="unset"
              />
              <MessageFromAnotherUserDev
                fromUserText="All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary "
                time="18:35"
                messageFromAnotherUserDevWidth="unset"
                messageFromAnotherUserDevPosition="absolute"
                messageFromAnotherUserDevTop="104px"
                messageFromAnotherUserDevRight="unset"
                messageFromAnotherUserDevLeft="calc(50% - 322px)"
                messageFromAnotherUserDevBorderRadius="16px 16px 0px 16px"
                allTheLoremFlex="unset"
                allTheLoremWidth="676px"
                allTheLoremDisplay="inline-block"
              />
            </div>
          </div>
          <StateDefaultVariantMessage
            yourMessage="Your message"
            hugeIconcommunicationsoli="/hugeiconcommunicationsolidsentfast2@2x.png"
            stateDefaultVariantMessagPosition="unset"
            stateDefaultVariantMessagWidth="unset"
            stateDefaultVariantMessagRight="unset"
            stateDefaultVariantMessagBottom="unset"
            stateDefaultVariantMessagLeft="unset"
            stateDefaultVariantMessagAlignSelf="stretch"
            searchInputWidth="unset"
            searchInputFlex="1"
            searchInputPadding="12px 16px"
            yourMessageFlex="1"
            yourMessageFontSize="20px"
            yourMessageLineHeight="28px"
            yourMessageColor="#bbb"
            yourMessageWidth="unset"
            yourMessageDisplay="unset"
            hugeIconcommunicationsoliWidth="32px"
            hugeIconcommunicationsoliHeight="32px"
          />
        </div>
      </div>
    </div>
  );
};

export default DChatMessage;
